cache:
  apt: true
  directories:
    - node_modules

git:
  depth: 2

branches:
  only:
    - master
    - develop

language: node_js

node_js:
  - "6.9.2"
  - "6.1"
  - "5.11"
  - "5.0"
  - "4.4"
  - "4.0"

before_install:
  - t=4.0.5 && v=`npm -v` && x=`printf "$v\n$t" | sort -V | head -n 1` && [ $x != $t ] && npm install -g npm || echo "no need to upgrade npm."

install:
  - npm install
  - npm install -g gulp

script:
  - npm run lint
  - npm run test-cov
